services:
  db:
    build: ./db
    ports:
      - "3002:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_user
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_passwd
      - MONGO_INITDB_DATABASE=abiotic_assistant
    secrets:
      - mongo_user
      - mongo_passwd
      - mongo_api_user
      - mongo_api_passwd
  backend:
    build: ./backend
    ports:
      - "3001:3000"
    volumes:
      - ./backend/src:/app/src
    environment:
      - ABIOTIC_DEV=1
      - ABIOTIC_DEBUG=1
      - ABIOTIC_PORT=3000
      - ABIOTIC_MONGO_DB=abiotic_assistant
    secrets:
      - mongo_api_user
      - mongo_api_passwd
  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app

secrets:
  mongo_user:
    file: ./db/mongo_user
  mongo_passwd:
    file: ./db/mongo_passwd
  mongo_api_user:
    file: ./db/mongo_api_user
  mongo_api_passwd:
    file: ./db/mongo_api_passwd
