services:
  backend:
    build: ./backend
    ports:
      - "8080:3000"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
